-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Imperator Averzian", {
	[1249251] = "yellow",
	[1249262] = "orange",
	[1251361] = "cyan",
	[1258883] = "cyan",
	[1260712] = "purple",
	[1280015] = "yellow",
})

BigWigs:AddSounds("Imperator Averzian", {
	[1249251] = "alert",
	[1249262] = "warning",
	[1251361] = "long",
	[1258883] = "long",
	[1260712] = "alarm",
})

BigWigs:AddColors("Vorasius", {
	[1241692] = "yellow",
	[1254199] = "cyan",
	[1256855] = "red",
	[1260052] = "orange",
})

BigWigs:AddSounds("Vorasius", {
	[1241692] = "alert",
	[1254199] = "long",
	[1256855] = "warning",
	[1260052] = "alarm",
})

BigWigs:AddColors("Fallen-King Salhadaar", {
	[1246175] = "red",
	[1247738] = "orange",
	[1248697] = "yellow",
	[1250686] = "yellow",
	[1250803] = "purple",
	[1254081] = "red",
})

BigWigs:AddSounds("Fallen-King Salhadaar", {
	[1246175] = "warning",
	[1247738] = "alarm",
	[1250686] = "alert",
	[1254081] = "warning",
})

BigWigs:AddColors("Vaelgor & Ezzorak", {
	[1244221] = "red",
	[1244917] = "orange",
	[1245391] = "orange",
	[1245645] = "purple",
	[1249748] = "yellow",
	[1262623] = "yellow",
	[1265131] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Vaelgor & Ezzorak", {
	[1244917] = "alarm",
	[1245391] = "alert",
	[1245645] = "alarm",
	[1249748] = "alert",
	[1262623] = "alert",
	[1265131] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Lightblinded Vanguard", {
	[1246162] = "cyan",
	[1246485] = "yellow",
	[1246736] = "purple",
	[1246749] = "yellow",
	[1246765] = "red",
	[1248449] = "cyan",
	[1248451] = "cyan",
	[1248644] = "orange",
	[1248674] = "red",
	[1248710] = "orange",
	[1248983] = "red",
	[1251857] = "purple",
	[1255738] = "orange",
	[1276243] = "cyan",
})

BigWigs:AddSounds("Lightblinded Vanguard", {
	[1246162] = "long",
	[1246736] = "info",
	[1246749] = "alert",
	[1246765] = "alarm",
	[1248449] = "long",
	[1248451] = "long",
	[1248644] = "warning",
	[1248674] = "warning",
	[1251857] = "info",
	[1255738] = "alert",
	[1276243] = "info",
})

BigWigs:AddColors("Crown of the Cosmos", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Crown of the Cosmos", {
})
