-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Imperator Averzian", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Imperator Averzian", {
})

BigWigs:AddColors("Vorasius", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Vorasius", {
})

BigWigs:AddColors("Fallen-King Salhadaar", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Fallen-King Salhadaar", {
})

BigWigs:AddColors("Vaelgor & Ezzorak", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Vaelgor & Ezzorak", {
})

BigWigs:AddColors("Lightblinded Vanguard", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Lightblinded Vanguard", {
})

BigWigs:AddColors("Crown of the Cosmos", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Crown of the Cosmos", {
})
