-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Chimaerus the Undreamt God", {
	[1245396] = "red",
	[1245406] = "cyan",
	[1245486] = "red",
	[1246621] = "red",
	[1246653] = "yellow",
	[1257085] = "red",
	[1257087] = "yellow",
	[1258610] = "cyan",
	[1264756] = "yellow",
	[1272726] = "purple",
	["berserk"] = {"orange","red"},
	["stages"] = "red",
})

BigWigs:AddSounds("Chimaerus the Undreamt God", {
	[1245396] = "warning",
	[1245406] = "long",
	[1245486] = "warning",
	[1246621] = "alert",
	[1246653] = "alert",
	[1257085] = "info",
	[1257087] = "alert",
	[1258610] = "long",
	[1262289] = "warning",
	[1264756] = "alert",
	[1272726] = "alert",
	["berserk"] = "alarm",
	["stages"] = "long",
})
