-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Chimaerus the Undreamt God", {
	[1245396] = "red",
	[1245406] = "red",
	[1245486] = "red",
	[1246621] = "red",
	[1246653] = "yellow",
	[1257085] = "red",
	[1257087] = "yellow",
	[1258610] = "yellow",
	[1262289] = "yellow",
	[1264756] = "yellow",
	[1272726] = "yellow",
	["berserk"] = {"orange","red","yellow"},
})

BigWigs:AddSounds("Chimaerus the Undreamt God", {
	[1245396] = "long",
	[1245406] = "long",
	[1245486] = "long",
	[1246621] = "long",
	[1246653] = "alert",
	[1257085] = "long",
	[1257087] = "alert",
	[1258610] = "alert",
	[1262289] = "alert",
	[1264756] = "alert",
	[1272726] = "alert",
	["berserk"] = "alarm",
})
