-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Belo'ren, Child of Al'ar", {
	[1241282] = "cyan",
	[1242260] = "orange",
	[1242515] = "cyan",
	[1242981] = "red",
	[1244344] = "yellow",
	[1260763] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Belo'ren, Child of Al'ar", {
	[1241282] = "info",
	[1242515] = "long",
	[1244344] = "alert",
	[1260763] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Midnight Falls", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Midnight Falls", {
})
