-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Belo'ren, Child of Al'ar", {
	[1241282] = "cyan",
	[1242260] = "orange",
	[1242515] = "cyan",
	[1242981] = "red",
	[1244344] = "yellow",
	[1260763] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Belo'ren, Child of Al'ar", {
	[1241282] = "info",
	[1242515] = "long",
	[1244344] = "alert",
	[1260763] = "alert",
	["stages"] = {"info","long"},
})

BigWigs:AddColors("Midnight Falls", {
	[1249620] = "red",
	[1250898] = "red",
	[1251386] = "yellow",
	[1253915] = "orange",
	[1266388] = "yellow",
	[1266897] = "orange",
	[1267049] = "purple",
	[1279420] = "yellow",
	[1282412] = "yellow",
	[1284525] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Midnight Falls", {
	[1249620] = "warning",
	[1250898] = "warning",
	[1251386] = "alert",
	[1253915] = "alarm",
	[1266897] = "alert",
	[1267049] = "alert",
	[1279420] = "info",
	[1282412] = "alarm",
	[1284525] = "alert",
	["stages"] = "long",
})
