-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Belo'ren, Child of Al'ar", {
	[1241282] = "cyan",
	[1241292] = {"blue","red"},
	[1241313] = "cyan",
	[1242260] = {"blue","orange"},
	[1242515] = "cyan",
	[1242981] = "red",
	[1244344] = "yellow",
	[1246709] = "red",
	[1260763] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Belo'ren, Child of Al'ar", {
	[1241282] = "info",
	[1241313] = "long",
	[1242515] = "long",
	[1244344] = "alert",
	[1246709] = "warning",
	[1260763] = "alert",
	["stages"] = "info",
})

BigWigs:AddColors("Midnight Falls", {
	[1249609] = "blue",
	[1249620] = "red",
	[1250898] = "red",
	[1251386] = "yellow",
	[1253915] = "orange",
	[1266388] = "yellow",
	[1266897] = "orange",
	[1267049] = "purple",
	[1273158] = "red",
	[1276525] = "red",
	[1279420] = "yellow",
	[1282412] = "yellow",
	[1282441] = {"blue","orange"},
	[1282469] = "yellow",
	[1284525] = {"blue","orange"},
	[1284931] = "yellow",
	[1284980] = "red",
	["berserk"] = "red",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Midnight Falls", {
	[1249620] = "warning",
	[1250898] = "warning",
	[1251386] = "alert",
	[1253915] = "alarm",
	[1266388] = "info",
	[1266897] = "alert",
	[1267049] = "alert",
	[1273158] = "warning",
	[1276525] = "alert",
	[1279420] = "info",
	[1282412] = "alarm",
	[1282469] = "alert",
	[1284525] = "alert",
	[1284931] = "alert",
	[1284980] = "warning",
	["berserk"] = "alarm",
	["stages"] = "long",
})
