-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Lu'ashal", {
	[1258427] = "red",
	[1276247] = "purple",
	[1276427] = {"blue","yellow"},
})

BigWigs:AddSounds("Lu'ashal", {
	[1258427] = "warning",
	[1276247] = "long",
	[1276427] = "alarm",
})
