-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rotmire", {
	[1221622] = "cyan",
	[1221637] = "red",
	[1221781] = "purple",
	[1221787] = "yellow",
	[1222088] = "blue",
})

BigWigs:AddSounds("Rotmire", {
	[1221622] = "long",
	[1221637] = "long",
	[1221781] = "alert",
})
