-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Rotmire", {
	[1221622] = "cyan",
	[1221637] = "red",
	[1221781] = {"blue","purple"},
	[1221787] = "orange",
	[1222088] = {"blue","yellow"},
	["berserk"] = {"orange","red"},
})

BigWigs:AddSounds("Rotmire", {
	[1221622] = "info",
	[1221637] = "long",
	[1221781] = {"alert","warning"},
	[1221787] = "alarm",
	["berserk"] = "alarm",
})
