name: Check PR

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout addon
        uses: actions/checkout@v6

      - name: Run luacheck
        uses: BigWigsMods/luacheck@main
        with:
          args: -q

      - name: Lint boss modules
        if: always()
        uses: BigWigsMods/luacheck@main
        with:
          run_luacheck: false
          custom_script: gen_option_values.lua
          custom_args: -q -n BigWigs.toc
