-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Nek'zali the Soulcoiler", {
	[1287426] = "blue",
	[1292036] = "purple",
	[1293212] = "cyan",
	[1295397] = "cyan",
	[1299673] = "orange",
	[1305421] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nek'zali the Soulcoiler", {
	[1293212] = "long",
	[1295397] = "info",
	[1299673] = "alarm",
	["stages"] = "long",
})
