-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Nek'zali the Soulcoiler", {
	[1287426] = "blue",
	[1292036] = "purple",
	[1293212] = "cyan",
	[1295397] = "cyan",
	[1299673] = "orange",
	[1305421] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nek'zali the Soulcoiler", {
	[1293212] = "long",
	[1295397] = "info",
	[1299673] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Entombed Sentinels", {
	[1284251] = "cyan",
	[1284434] = "yellow",
	[1284458] = "purple",
	[1284483] = "yellow",
	[1284487] = "purple",
	[1284588] = {"cyan","green"},
	[1288232] = {"blue","orange"},
	[1296878] = "red",
	["berserk"] = "red",
})

BigWigs:AddSounds("Entombed Sentinels", {
	[1284251] = "info",
	[1284458] = "alert",
	[1284483] = "alert",
	[1284487] = "alert",
	[1284588] = "long",
	[1288232] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Lost Explorers", {
	[1286921] = "yellow",
	[1290711] = "blue",
	[1291390] = "red",
	[1291759] = "orange",
	[1291933] = "yellow",
	[1292104] = "green",
	[1292779] = "red",
	[1295817] = "green",
	[1295854] = "purple",
	[1295886] = "orange",
	[1296092] = "orange",
	[1296249] = "red",
	[1296535] = {"blue","green"},
	[1297022] = {"cyan","green"},
})

BigWigs:AddSounds("The Lost Explorers", {
	[1291390] = "alarm",
	[1291759] = "alarm",
	[1291933] = "alert",
	[1292104] = "info",
	[1292779] = "alarm",
	[1295817] = "info",
	[1295854] = "alert",
	[1296092] = "alert",
	[1296249] = "alarm",
	[1296535] = "info",
	[1297022] = "long",
})

BigWigs:AddColors("Vashnik the Malignant", {
	[1280935] = "purple",
	[1281907] = "yellow",
	[1282117] = "red",
	[1282525] = "orange",
	[1283164] = "cyan",
})

BigWigs:AddSounds("Vashnik the Malignant", {
	[1282525] = "alert",
	[1283164] = "long",
})

BigWigs:AddColors("Sszorak", {
	[1277025] = "purple",
	[1285425] = {"blue","orange"},
	[1285732] = "red",
	[1296898] = "red",
	[1305959] = "yellow",
})

BigWigs:AddSounds("Sszorak", {
	[1277025] = "alert",
	[1285732] = "long",
	[1296898] = "alarm",
	[1305959] = "alarm",
})

BigWigs:AddColors("The Twin Fangs", {
	[1288538] = "purple",
	[1289192] = "orange",
	[1290516] = "orange",
	[1290809] = {"blue","yellow"},
	[1290956] = "orange",
	[1291404] = "cyan",
	[1291478] = "orange",
	[1294293] = "yellow",
	[1303230] = "yellow",
	[1306872] = "yellow",
	[1308356] = "red",
	[1308556] = "cyan",
})

BigWigs:AddSounds("The Twin Fangs", {
	[1289192] = "alarm",
	[1290516] = "alarm",
	[1290809] = "warning",
	[1290956] = "alarm",
	[1291404] = "info",
	[1291478] = "alarm",
	[1294293] = "long",
	[1303230] = "alert",
	[1306872] = "alert",
	[1308356] = "warning",
	[1308556] = "info",
})

BigWigs:AddColors("The Coiled Altar", {
	[1282281] = "yellow",
	[1282487] = "red",
	[1283489] = "orange",
	[1283832] = "yellow",
	[1285911] = "blue",
	[1286441] = "cyan",
	[1286573] = "purple",
	[1286895] = "blue",
	[1286918] = "red",
	[1289900] = "orange",
	[1298381] = "red",
	[1299266] = "orange",
	[1299680] = "purple",
	[1299960] = "yellow",
	[1307279] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Coiled Altar", {
	[1282281] = "alarm",
	[1282487] = "alarm",
	[1283489] = "alert",
	[1283832] = "alarm",
	[1286441] = "info",
	[1286573] = "alert",
	[1286918] = "alarm",
	[1289900] = "alert",
	[1298381] = "alarm",
	[1299266] = "alert",
	[1299680] = "alert",
	[1299960] = "info",
	[1307279] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Ula'tek", {
	[1286860] = {"green","yellow"},
	[1286905] = "red",
	[1292188] = "red",
	[1295905] = "orange",
	[1296301] = "yellow",
	[1298367] = "purple",
	[1298559] = "cyan",
	[1300530] = "orange",
	[1300751] = "yellow",
	[1301510] = "red",
	[1302982] = "yellow",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Ula'tek", {
	[1286860] = {"info","long"},
	[1286905] = "alarm",
	[1292188] = "warning",
	[1295905] = "alert",
	[1296301] = "alarm",
	[1298367] = "alert",
	[1298559] = "info",
	[1300530] = "alert",
	[1300751] = "alarm",
	[1301510] = "long",
	[1302982] = "alarm",
	["stages"] = "long",
})
