-- This file is automatically generated for packaged releases. Changes made here are only relevant when running from source.

BigWigs:AddColors("Nek'zali the Soulcoiler", {
	[1287426] = "blue",
	[1292036] = "purple",
	[1293212] = "cyan",
	[1295397] = "cyan",
	[1299673] = "orange",
	[1305421] = "orange",
	["stages"] = "cyan",
})

BigWigs:AddSounds("Nek'zali the Soulcoiler", {
	[1293212] = "long",
	[1295397] = "info",
	[1299673] = "alarm",
	["stages"] = "long",
})

BigWigs:AddColors("Entombed Sentinels", {
	[1284251] = "cyan",
	[1284434] = "yellow",
	[1284458] = "purple",
	[1284483] = "yellow",
	[1284487] = "purple",
	[1284588] = {"cyan","green"},
	[1288232] = {"blue","orange"},
	[1296878] = "red",
	["berserk"] = "red",
})

BigWigs:AddSounds("Entombed Sentinels", {
	[1284251] = "info",
	[1284458] = "alert",
	[1284483] = "alert",
	[1284487] = "alert",
	[1284588] = "long",
	[1288232] = "alert",
	["berserk"] = "alarm",
})

BigWigs:AddColors("The Lost Explorers", {
	[1286921] = "yellow",
	[1290711] = "blue",
	[1291390] = "red",
	[1291759] = "orange",
	[1291933] = "yellow",
	[1292104] = "green",
	[1292779] = "red",
	[1295817] = "green",
	[1295854] = "purple",
	[1295886] = "orange",
	[1296092] = "orange",
	[1296249] = "red",
	[1296535] = {"blue","green"},
	[1297022] = {"cyan","green"},
})

BigWigs:AddSounds("The Lost Explorers", {
	[1291390] = "alarm",
	[1291759] = "alarm",
	[1291933] = "alert",
	[1292104] = "info",
	[1292779] = "alarm",
	[1295817] = "info",
	[1295854] = "alert",
	[1296092] = "alert",
	[1296249] = "alarm",
	[1296535] = "info",
	[1297022] = "long",
})

BigWigs:AddColors("Sszorak", {
	[1277025] = "purple",
	[1285425] = {"blue","orange"},
	[1285732] = "red",
	[1296898] = "red",
	[1305959] = "yellow",
})

BigWigs:AddSounds("Sszorak", {
	[1277025] = "alert",
	[1285732] = "long",
	[1296898] = "alarm",
	[1305959] = "alarm",
})

BigWigs:AddColors("The Coiled Altar", {
	[1282281] = "yellow",
	[1282487] = "red",
	[1283489] = "orange",
	[1283832] = "yellow",
	[1285911] = "blue",
	[1286441] = "cyan",
	[1286573] = "purple",
	[1286895] = "blue",
	[1286918] = "red",
	[1289900] = "orange",
	[1298381] = "red",
	[1299266] = "orange",
	[1299680] = "purple",
	[1299960] = "yellow",
	[1307279] = "purple",
	["stages"] = "cyan",
})

BigWigs:AddSounds("The Coiled Altar", {
	[1282281] = "alarm",
	[1282487] = "alarm",
	[1283489] = "alert",
	[1283832] = "alarm",
	[1286441] = "info",
	[1286573] = "alert",
	[1286918] = "alarm",
	[1289900] = "alert",
	[1298381] = "alarm",
	[1299266] = "alert",
	[1299680] = "alert",
	[1299960] = "info",
	[1307279] = "alert",
	["stages"] = "long",
})

BigWigs:AddColors("Ula'tek", {
	["stages"] = "yellow",
})

BigWigs:AddSounds("Ula'tek", {
})
